### ISSUE TITLE
用不了，两个都是

### ISSUE THREAD

**Issue by iower2logseq** [samwei12/LogseqMisc#1]
是不是桌面版本就用不了，原版跟您做的这个都用不了，直接模板都是显示不了，四象限的视图也触发不了。

**Comment by samwei12** [comment]
> 是不是桌面版本就用不了，原版跟您做的这个都用不了，直接模板都是显示不了，四象限的视图也触发不了。

金丝雀版本目前有点问题，css的选择器无法触发，已经提了bug，等修复吧
